MixedDjango/clonecodding/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy, re_path
from . import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_veiw, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('follow_recommend/', views.follow_recommend, name='follow_recommend'),
    path('follower_list/', views.follower_list, name='follower_list'),
    re_path(r'^(?P<username>[\w.@+-]+)/follows/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollows/$', views.user_unfollow, name='user_unfollow'),
    path('api-token-auth/', obtain_auth_token)
]

MixedDjango/clonecodding/instagram/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include, re_path
from . import views
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register('post', views.PostViewSet)


app_name = 'instagram'

urlpatterns = [
    path('post_create/', views.post_create, name='post_create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<int:pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    # re_path(r'^(?P<pk>[0-9]+)/comment_edit/(?P<comment_pk>[0-9]+)/$', views.comment_edit, name='comment_edit'),
    path('<int:pk>/comment_edit/<int:comment_pk>/', views.comment_edit, name='comment_edit'),
    path('<int:pk>/post_update/', views.post_update, name='post_update'),
    path('<int:pk>/post_delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/post_like/', views.post_like, name='post_like'),
    path('<int:pk>/post_unlike/', views.post_unlike, name='post_unlike'),
    path('', include(router.urls)),
    path('mypost/<int:pk>/', views.PostDetailAPIView.as_view())
]

MixedDjango/clonecodding/instagram/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.CharField(max_length=300)
    photo = models.ImageField(upload_to="instagram/post/%Y/%m/%d", blank=True)
    tag = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post_set", blank=True)

    class Meta:
        ordering = ['-id']

    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])

    def is_like_user(self, user):
        return self.like_user.filter(pk=user.pk).exists()


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()


class Tag(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

MixedDjango/clonecodding/instagram/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', 'photo', 'tag']
        widgets = {'message': forms.Textarea}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

MixedDjango/clonecodding/instagram/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.views.generic import ListView, UpdateView, CreateView, DetailView, DeleteView
from django.contrib import messages
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.renderers import TemplateHTMLRenderer

from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.urls import reverse, reverse_lazy
from django.contrib.auth import get_user_model


# 함수기반
# def post_list(request):
#     post_list = Post.objects.filter(author=request.user)
#
#
#     return render(request, 'instagram/post_list.html', {
#         'post_list': post_list
#     })
#
# def post_create(request):
#     form = PostForm(request.POST, request.FILES)
#     pass
#
# def post_modify(request, pk):
#     pass
#
# def post_delete(request, pk):
#     pass


class PostListView(ListView):

    # def get_queryset(self):
    # get_queryset의 다음에 페이지네이터가 구현되어 있어서 paginate_by를 쓸 수 있다
    #         if not self.request.user.is_anonymous:
    #             self.queryset = Post.objects.filter(author=self.request.user)
    #             if not self.queryset:
    #                 self.queryset = None
    #             return self.queryset
    def get(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            qs = Post.objects.all() \
                .filter(
                Q(author__in=request.user.following_set.all()) |
                Q(author=request.user)
            )
            if qs:
                paginator, page, queryset, is_paginated = super().paginate_queryset(qs, 9)
                context = {
                    'paginator': paginator,
                    'page': page,
                    'is_paginated': is_paginated,
                    'post_list': queryset,
                }
                return render(request, 'instagram/post_list.html', context)
        return render(request, 'instagram/post_list.html', {
            'post_list': None
        })


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        messages.success(self.request, '포스팅 저장 완료')
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(Post, pk=kwargs['pk'])
        if self.object.author != request.user:
            messages.warning(self.request, '작성한 회원만 수정할 수 있습니다')
            return redirect(self.object)
        form = PostForm
        return super(PostUpdateView, self).get(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.author == self.request.user:
            messages.success(self.request, '포스팅 수정 완료')
            form.save()
        else:
            messages.warning(self.request, '작성한 회원만 수정할 수 있습니다')
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name_suffix = '_delete'
    success_url = 'instagram/post_list.html'

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(Post, pk=kwargs['pk'])
        if self.object.author != request.user:
            messages.warning(self.request, '작성한 회원만 삭제할수 있습니다')
            return redirect(self.object)
        return super(PostDeleteView, self).get(Post)

    def post(self, request, *args, **kwargs):
        self.object = get_object_or_404(Post, pk=kwargs['pk'])
        if self.object.author != request.user:
            messages.warning(self.request, '작성한 회원만 삭제할수 있습니다')
            return redirect(self.object)
        self.object.delete()
        messages.success(request, '포스팅 삭제 완료')
        return redirect('instagram:post_list')


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        comment_list = Comment.objects.filter(post=kwargs.get('object'))
        comment_form = CommentForm()
        context = {
            'comment_list': comment_list,
            'form': comment_form
        }
        return super().get_context_data(**context)

    def post(self, request, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = super().get_object()
            comment.save()
            return redirect('instagram:post_detail', pk=kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        pk = request.GET.get('pk', '')

        if pk:
            comment = Comment.objects.get(pk=pk)
            if comment.author != request.user:
                messages.warning(request, message="작성자가 아닙니다")
                return

            self.object = self.get_object()
            initial_dict = {
                "comment": comment.comment,
                "author": comment.author,
                "post": comment.post,
            }
            form = CommentForm(request.POST or None, initial=initial_dict)
            self.object = self.get_object()
            context = self.get_context_data(object=self.object)
            context["comment_edit_form"] = form
            context["comment_pk"] = comment.pk
            return self.render_to_response(context)
            # return render(request, "instagram/form.html", {
            #     "comment_edit_form": comment_edit_form,
            #     "comment_message": comment.comment
            # })

        else:
            self.object = self.get_object()
            context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('instagram:post_detail', pk=pk)

    else:
        comment_list = Comment.objects.filter(post=pk)
        comment_form = CommentForm()

    return render(request, 'instagram/post_detail.html', {
        'post': post,
        'form': comment_form,
        'comment_list': comment_list,
    })


def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user==post.author:
        messages.warning(request, "작성한 회원은 좋아요를 누를수 없습니다")
        return redirect('instagram:post_detail', pk=pk)
    post.like_user.add(request.user)
    messages.success(request, f"{post.author} 좋아요")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)


def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user.remove(request.user)
    messages.success(request, f"{post.author} 좋아요 취소")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)


def comment_delete(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect('instagram:post_detail', pk=pk)


def comment_edit(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    form = CommentForm(request.POST or None,
                       instance=comment)
    if request.method == 'POST':
        if form.is_valid():
            comment_form = form.save(commit=False)
            comment_form.comment = request.POST.get("comment")
            comment_form.save()

    return redirect('instagram:post_detail', pk=pk)


# 함수기반
# @login_required
# def post_delete(request, pk):
#     model = Post
#     post = get_object_or_404(model, pk=pk)
#     if post.author == request.user:
#         messages.warning(request, '정말 삭제 하시겠습니까?')
#         if request.method == 'POST':
#             post.delete()
#             messages.success(request, '포스팅 삭제 완료')
#             return redirect('instagram:post_list')
#     else:
#         messages.warning(request, '작성한 회원만 삭제할 수 있습니다')
#         return redirect(post)
#     return render(request, 'instagram/post_delete.html', {
#     })


post_create = PostCreateView.as_view()
post_update = PostUpdateView.as_view()
post_list = PostListView.as_view()
post_delete = PostDeleteView.as_view()

#######################################

from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from .serializers import PostSerializer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import generics
from rest_framework.generics import RetrieveAPIView
from rest_framework.decorators import api_view, action
from rest_framework.permissions import IsAuthenticated
from .permissions import IsAuthorOrReadonly

class PostViewSet(ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticated, IsAuthorOrReadonly]
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields=['message']
    ordering=['id']
    @action(detail=False, methods=['GET'])
    def message(self, request):
        qs = self.get_queryset().filter(message__startswith='1')
        serializer = self.get_serializer(qs, many=True)
        return Response(serializer.data)

    @action(detail=True, methods=['PATCH'])
    def message_set(self, request, pk):
        instance = self.get_object()
        instance.message = '바뀜'
        instance.save(update_fields=['message'])
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

MixedDjango/clonecodding/instagram/templates/instagram/comment.html
{% load bootstrap4 %} {% block content %}
<div class="container">
    {% if comment_list %}
    <div class="container">
        {% for comment in comment_list %}
        <div class="col">
            <div>작성자 :{{comment.author}}</div>
            <div>{{comment.comment}}</div>
            {% if request.user == comment.author %}
            <div class="container">
                <div class="">
                    <form action="" method="get">
                        <input type="hidden" value="{{ comment.pk }}" name="pk" />
                        <input type="submit" value="수정"/>
                    </form>

                    <a href="{% url 'instagram:comment_delete' post.pk comment.pk %}">삭제</a>
                </div>
            </div>
            {% endif %}
        </div>
        <hr/>
        {% endfor %}
    </div>
    {% endif %}
</div>
<div class="container">
    {% if comment_edit_form %}
        {% include "instagram/form.html" with submit_label="코멘트 수정" %}
    {% else %}
        {% include "form.html" with submit_label="코멘트 저장" %}
    {% endif %}
</div>
{% endblock %}

MixedDjango/clonecodding/instagram/templates/instagram/form.html
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <div class="row">
        <form method="post" action="{% url 'instagram:comment_edit' post.pk comment_pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form comment_edit_form %}
            <button type="submit" class="btn btn-primary mt-2">
                {{ submit_label|default:"Submit" }}
            </button>
        </form>
    </div>
</div>
{% endblock %}

MixedDjango/clonecodding/instagram/templates/instagram/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

MixedDjango/clonecodding/instagram/templates/instagram/mypost.html
{{post}}

{{post.author}}
{{post.message}}

MixedDjango/clonecodding/instagram/templates/instagram/post_delete.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    <div class="alert alert-danger" role="alert">
 정말 삭제하시겠습니까?
</div>
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">삭제하기</button>
</form>
{% endblock %}

MixedDjango/clonecodding/instagram/templates/instagram/post_detail.html
{% extends "base.html" %}
{% load bootstrap4 instagram_tags humanize %}
{% block content %}
<div class="container-xxl">
    <div class="container">
        <div class="card text-center">
            {% if post.photo %}
            <img src="{{ post.photo.url }}" class="rounded mx-auto d-block" alt="post_photo" style="width:25%">
            {% else %}
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"></rect>
                <text x="38%" y="50%" fill="#eceeef" dy=".3em">이미지 없음</text>
            </svg>
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ post.author }}</h5>
                <p class="card-text">{{ post.message }}</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>

        </div>
        <div class="container mt-3 text-end">
                {% if post|is_like_user:user %}
                <i class="bi bi-heart-fill"></i>
                <a href="{% url 'instagram:post_unlike' post.pk %}" style="color: inherit;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-heart-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                              d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                    </svg>
                </a>

                {% else %}
                <i class="bi bi-heart"></i>
                <a href="{% url 'instagram:post_like' post.pk %}" style="color: inherit;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                    </svg>
                </a>
                {% endif %}
            {% if request.user == post.author %}
                <a href="{% url 'instagram:post_update' post.id %}" class="btn btn-primary">포스팅 수정</a>
                <a href="{% url 'instagram:post_delete' post.id %}" class="btn btn-primary">포스팅 삭제</a>
            {% endif %}
        </div>
    </div>
    <hr />
    <div class="container">
        <div class="container">댓글</div>
        {% include 'instagram/comment.html' %}
    </div>

</div>

{% endblock %}

MixedDjango/clonecodding/instagram/templates/instagram/post_form.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
    {% include "form.html" with submit_label="포스트 저장" %}
{% endblock %}

MixedDjango/clonecodding/instagram/templates/instagram/post_list.html
{% load bootstrap4 %}
{% if post_list %}
{% for post in post_list %}

<div class="col">
    <div class="card shadow-sm d-flex justify-content-center">
        {% if post.photo %}
        <img src="{{ post.photo.url }}" class="bd-placeholder-img card-img-top mx-auto d-block"
             style="width:25%;"/>
        {% else %}
        <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
             xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c"></rect>
            <text x="40%" y="50%" fill="#eceeef" dy=".3em">이미지 없음</text>
        </svg>
        {% endif %}
        <div class="card-body">
            <p class="card-text">
                {% if post.message %}
                {{ post.message }}
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"
                            onclick="location.href='{% url 'instagram:post_detail' post.id %}'">View
                    </button>
                </div>
                <small class="text-muted">9 mins</small>
            </div>
        </div>
    </div>
</div>

{% endfor %}
{% endif %}

MixedDjango/clonecodding/instagram/templates/instagram/post_update.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
{% include "form.html" with submit_label="포스트 수정" %}
{% buttons %}
{% endbuttons %}
{% endblock %}