MixedDjango/clonecodding/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy, re_path
from . import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_veiw, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('follow_recommend/', views.follow_recommend, name='follow_recommend'),
    path('follower_list/', views.follower_list, name='follower_list'),
    re_path(r'^(?P<username>[\w.@+-]+)/follows/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollows/$', views.user_unfollow, name='user_unfollow'),
    path('api-token-auth/', obtain_auth_token)
]

MixedDjango/clonecodding/instagram/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include, re_path
from . import views
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register('post', views.PostViewSet)


app_name = 'instagram'

urlpatterns = [
    path('post_create/', views.post_create, name='post_create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<int:pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    # re_path(r'^(?P<pk>[0-9]+)/comment_edit/(?P<comment_pk>[0-9]+)/$', views.comment_edit, name='comment_edit'),
    path('<int:pk>/comment_edit/<int:comment_pk>/', views.comment_edit, name='comment_edit'),
    path('<int:pk>/post_update/', views.post_update, name='post_update'),
    path('<int:pk>/post_delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/post_like/', views.post_like, name='post_like'),
    path('<int:pk>/post_unlike/', views.post_unlike, name='post_unlike'),
    path('', include(router.urls)),
    path('mypost/<int:pk>/', views.PostDetailAPIView.as_view())
]

MixedDjango/clonecodding/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth import get_user_model
from django_auto_one_to_one import AutoOneToOneModel


class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=128)
    following_set = models.ManyToManyField("self", blank=True)
    follower_set = models.ManyToManyField("self", blank=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(max_length=254, blank=True)






def user_profile_path(instance, filename):
    return 'instagram/profile/user_{}/{}'.format(instance.user, filename)


class Profile(AutoOneToOneModel(User)):
    user_photo = models.ImageField(blank=True, upload_to=user_profile_path)
    status_message = models.CharField(blank=True, max_length=300)

MixedDjango/clonecodding/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms.models import ModelForm

from accounts.models import Profile


class UserForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = ['user_photo', 'status_message']

MixedDjango/clonecodding/accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from .forms import UserForm, ProfileForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model, login
from .models import Profile, User
from instagram.models import Post






class LoginView(LoginView):
    model = get_user_model()
    template_name = 'accounts/login.html'


def signup_view(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:profile')
    else:
        form = UserForm
    return render(request, 'accounts/signup.html', {
        'form': form,
    })


class LogoutView(LogoutView):
    next_page = reverse_lazy('accounts:login')


@login_required
def profile_view(request):
    profile = get_object_or_404(Profile, user_id=request.user.pk)
    # post_list = Post.objects.get(pk=request.user.pk)
    post_list = Post.objects.all() \
                .filter(
                Q(author__in=request.user.following_set.all()) |
                Q(author=request.user)
    )

    return render(request, 'accounts/profile.html', {
        'profile': profile,
        'post_list': post_list,
    })

@login_required
def profile_edit(request):
    if request.POST:
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()
        return redirect('accounts:profile')
    profile = Profile.objects.get(pk=request.user.pk)
    profile_form = ProfileForm(instance=profile)
    return render(request, 'accounts/profile_edit_form.html', {
        'form': profile_form,
    })

@login_required
def follow_recommend(request):
    profile = get_object_or_404(Profile, user_id=request.user.pk)
    suggested_user_list = get_user_model().objects.all()\
            .exclude(pk=request.user.pk)\
            .exclude(pk__in=request.user.following_set.all())

    return render(request, 'accounts/profile.html', {
        'profile': profile,
        'suggested_user_list': suggested_user_list
    })

@login_required
def follower_list(request):
    profile = get_object_or_404(Profile, user_id=request.user.pk)
    follower_list = get_user_model().objects.all()\
            .exclude(pk=request.user.pk)\
            .filter(pk__in=request.user.following_set.all())

    return render(request, 'accounts/profile.html', {
        'profile': profile,
        'follower_list': follower_list
    })

def user_follow(request, username):
    follow_user = get_object_or_404(User, username=username, is_active=True)
    request.user.following_set.add(follow_user)
    follow_user.follower_set.add(request.user)
    messages.success(request, f"{follow_user}님을 팔로우 했습니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)

@login_required
def user_unfollow(request, username):
    unfollow_user = get_object_or_404(User, username=username, is_active=True)
    request.user.following_set.remove(unfollow_user)
    # unfollow_user.follower_set.remove(request.user)
    messages.success(request, f"{unfollow_user}님을 언팔로우 했습니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)

class ProfileView(ListView):


    # def get_queryset(self):
    # get_queryset의 다음에 페이지네이터가 구현되어 있어서 paginate_by를 쓸 수 있다
    #         if not self.request.user.is_anonymous:
    #             self.queryset = Post.objects.filter(author=self.request.user)
    #             if not self.queryset:
    #                 self.queryset = None
    #             return self.queryset
    def get(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            qs = Post.objects.all() \
                .filter(
                Q(author__in=request.user.following_set.all()) |
                Q(author=request.user)
            )
            if qs:
                paginator, page, queryset, is_paginated = super().paginate_queryset(qs, 9)
                context = {
                    'paginator': paginator,
                    'page': page,
                    'is_paginated': is_paginated,
                    'post_list': queryset,
                }
                return render(request, 'instagram/post_list.html', context)
        return render(request, 'instagram/post_list.html', {
            'post_list': None
        })





login_view = LoginView.as_view()
logout_veiw = LogoutView.as_view()

MixedDjango/clonecodding/accounts/templates/accounts/follow_recommend.html
{% block content %}
    {% if suggested_user_list %}
        <div class="container">
        <ul class="list-group">
            {% for suggested in suggested_user_list %}
                <div class="contanier">
                    <li class="list-group-item">{{suggested}}</li>
                    <a href="{% url 'accounts:user_follow' suggested %}">팔로우</a>
                </div>
            {% endfor %}
        </ul>
        </div>
    {% endif %}
{% endblock %}

MixedDjango/clonecodding/accounts/templates/accounts/follower_list.html
{% block content %}
    {% if follower_list %}
        <div class="container">
        <ul class="list-group">
            {% for follower in follower_list %}
                <div class="contanier">
                    <li class="list-group-item">{{follower}}</li>
                    <a href="{% url 'accounts:user_unfollow' follower %}">연팔로우</a>
                </div>
            {% endfor %}
        </ul>
        </div>
    {% endif %}
{% endblock %}

MixedDjango/clonecodding/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
{% include "form.html" with submit_label="로그인" %}
{% buttons %}

{% endbuttons %}
{% endblock %}

MixedDjango/clonecodding/accounts/templates/accounts/profile.html
{% extends "base.html" %}


{% block profile %}
<div class="container">
    <div class="container">
        <div class="row text-center">
            {% if profile %}
            {% if profile.user_photo %}
            <img src="{{ profile.user_photo.url }}" alt="{{ profile.user }}" class="rounded mx-auto d-block"
                 style="width:25%;align-content: center"/>
            {% else %}
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"></rect>
                <text x="38%" y="50%" fill="#eceeef" dy=".3em">이미지 없음</text>
            </svg>
            {% endif %}
            <div class="container">
            {{ profile.user }}
                </div>
            <div class="container">
                상태메세지
                <div>
                    {{ profile.status_message }}
                </div>
            </div>
            {% endif %}
            <div class="container mb-3">
                <a href="{% url 'instagram:post_create' %}" class="btn btn-primary">새 글 쓰기</a>
                <a class="btn btn-primary" href="{% url 'accounts:profile_edit' %}">프로필 편집</a>
            </div>
            <hr/>
        </div>
        <div>
            <div class="container">
                <ul class="nav justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' %}">게시물</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:follow_recommend' %}">팔로워 추천</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:follower_list' %}">팔로잉 리스트</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% include "instagram/post_list.html" %}
</div>
<div class="container mt-5">
    {% include "accounts/follow_recommend.html" %}
</div>
<div class="container mt-5">
    {% include "accounts/follower_list.html" %}
</div>
{% endblock %}

MixedDjango/clonecodding/accounts/templates/accounts/profile_edit_form.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
    {% include "form.html" with submit_label="프로필 저장" %}
{% endblock %}

MixedDjango/clonecodding/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
{% include "form.html" with submit_label="회원가입" %}
{% buttons %}
{% endbuttons %}
{% endblock %}