MixedDjango/clonecodding/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy, re_path
from . import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_veiw, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('follow_recommend/', views.follow_recommend, name='follow_recommend'),
    path('follower_list/', views.follower_list, name='follower_list'),
    re_path(r'^(?P<username>[\w.@+-]+)/follows/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollows/$', views.user_unfollow, name='user_unfollow'),
    path('api-token-auth/', obtain_auth_token)
]

MixedDjango/clonecodding/clonecodding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(pattern_name='accounts:profile'), name='root'),
    path('api-auth/', include('rest_framework.urls')),
    path('api-jwt-auth/', obtain_jwt_token),
    path('api-jwt-auth/refresh/', refresh_jwt_token),
    path('api-jwt-auth/verify/', verify_jwt_token),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG == True:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

MixedDjango/clonecodding/clonecodding/templates/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap5.0/css/bootstrap.css' %}">
    <script type="text/javascript" src="{% static 'bootstrap5.0/js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-body border-bottom shadow-sm">
        <div class="my-0 me-md-auto fw-normal" onclick="location.href='{% url 'accounts:profile' %}'" style="cursor:pointer;">
            <img alt="Instagram" class="s4Iyt" src="{% static 'img/logo.png'%}">
        </div>
        <nav class="my-2 my-md-0 me-md-3">
            <div class="Fifk5">
                <div class=""><a href="/" tabindex="0">
                    <svg aria-label="홈" class="_8-yf5 " fill="#262626" height="22" viewBox="0 0 48 48" width="22">
                        <path d="M45.3 48H30c-.8 0-1.5-.7-1.5-1.5V34.2c0-2.6-2-4.6-4.6-4.6s-4.6 2-4.6 4.6v12.3c0 .8-.7 1.5-1.5 1.5H2.5c-.8 0-1.5-.7-1.5-1.5V23c0-.4.2-.8.4-1.1L22.9.4c.6-.6 1.5-.6 2.1 0l21.5 21.5c.4.4.6 1.1.3 1.6 0 .1-.1.1-.1.2v22.8c.1.8-.6 1.5-1.4 1.5zm-13.8-3h12.3V23.4L24 3.6l-20 20V45h12.3V34.2c0-4.3 3.3-7.6 7.6-7.6s7.6 3.3 7.6 7.6V45z"></path>
                    </svg>
                </a></div>
            </div>
            <div class="Fifk5"><a class="xWeGp" href="/direct/inbox/" tabindex="0">
                <svg aria-label="Direct" class="_8-yf5 " fill="#262626" height="22" viewBox="0 0 48 48" width="22">
                    <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z"></path>
                </svg>
            </a></div>
            <div class="Fifk5"><a href="/explore/" tabindex="0">
                <svg aria-label="사람 찾기" class="_8-yf5 " fill="#262626" height="22" viewBox="0 0 48 48" width="22">
                    <path clip-rule="evenodd"
                          d="M24 0C10.8 0 0 10.8 0 24s10.8 24 24 24 24-10.8 24-24S37.2 0 24 0zm0 45C12.4 45 3 35.6 3 24S12.4 3 24 3s21 9.4 21 21-9.4 21-21 21zm10.2-33.2l-14.8 7c-.3.1-.6.4-.7.7l-7 14.8c-.3.6-.2 1.3.3 1.7.3.3.7.4 1.1.4.2 0 .4 0 .6-.1l14.8-7c.3-.1.6-.4.7-.7l7-14.8c.3-.6.2-1.3-.3-1.7-.4-.5-1.1-.6-1.7-.3zm-7.4 15l-5.5-5.5 10.5-5-5 10.5z"
                          fill-rule="evenodd"></path>
                </svg>
            </a></div>
            <div class="Fifk5"><a class="_0ZPOP kIKUG " href="/accounts/activity/">
                <svg aria-label="활동 피드" class="_8-yf5 " fill="#262626" height="22" viewBox="0 0 48 48" width="22">
                    <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path>
                </svg>
            </a>
                <div class="poA5q" style="margin-left: -423px;"></div>
            </div>
<!--                <div class="Fifk5">-->
<!--                    <div class="oZBNB"></div>-->
<!--                    <span class="_2dbep qNELH" role="link" tabindex="0" style="width: 22px; height: 22px;"><img-->
<!--                            alt="{{ user }}님의 프로필 사진" class="_6q-tv" crossorigin="anonymous" data-testid="user-avatar"-->
<!--                            draggable="false"-->
<!--                            src="https://scontent-sjc3-1.cdninstagram.com/v/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=scontent-sjc3-1.cdninstagram.com&amp;_nc_ohc=0CE398PqtLwAX_kgiM6&amp;oh=8b993e4a26427face1803e6399fbd9a1&amp;oe=6073AD0F&amp;ig_cache_key=YW5vbnltb3VzX3Byb2ZpbGVfcGlj.2"></span>-->
<!--                    <div class="poA5q" style="margin-left: -180px;"></div>-->
<!--                </div>-->-

        </nav>
        {% if not user.is_authenticated %}
            <a href="{% url 'accounts:login' %}" class="btn btn-primary me-2">로그인</a>
            <a href="{% url 'accounts:signup' %}" class="btn btn-primary">회원가입</a>
        {% else %}
            <div class="btn">{{ user }}</div>
            <a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}" class="btn btn-primary">로그아웃</a>
        {% endif %}
    </header>
    {% if messages %}
    {% bootstrap_messages %}
    {% endif %}

    <div class="album py-5 bg-light">

        <div class="container">
            {% block profile %}
            {% endblock %}
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>

        </div>

    </div>
    <div class="Page navigation example">
        <div class="pagination justify-content-center mt-3">
            {% if page %}
            {% bootstrap_pagination page %}
            {% endif %}
        </div>
    </div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="{% static 'bootstrap-logo.svg' %}" alt="" width="24" height="19">
        <small class="d-block mb-3 text-muted">© 2017–2021</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Cool stuff</a></li>
          <li><a class="link-secondary" href="#">Random feature</a></li>
          <li><a class="link-secondary" href="#">Team feature</a></li>
          <li><a class="link-secondary" href="#">Stuff for developers</a></li>
          <li><a class="link-secondary" href="#">Another one</a></li>
          <li><a class="link-secondary" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Resource</a></li>
          <li><a class="link-secondary" href="#">Resource name</a></li>
          <li><a class="link-secondary" href="#">Another resource</a></li>
          <li><a class="link-secondary" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Team</a></li>
          <li><a class="link-secondary" href="#">Locations</a></li>
          <li><a class="link-secondary" href="#">Privacy</a></li>
          <li><a class="link-secondary" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
    </div>
</body>
</html>

MixedDjango/clonecodding/clonecodding/templates/form.html
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <div class="row">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary mt-2">
                {{ submit_label|default:"Submit" }}
            </button>
        </form>
    </div>
</div>
{% endblock %}